/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnswersRouteImport } from './routes/answers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIosRouteImport } from './routes/services.ios'
import { Route as ServicesAppStoreSubmissionRouteImport } from './routes/services.app-store-submission'
import { Route as ServicesAndroidRouteImport } from './routes/services.android'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersRoute = AnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIosRoute = ServicesIosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAppStoreSubmissionRoute =
  ServicesAppStoreSubmissionRouteImport.update({
    id: '/app-store-submission',
    path: '/app-store-submission',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAndroidRoute = ServicesAndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => ServicesRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/services/android': typeof ServicesAndroidRoute
  '/services/app-store-submission': typeof ServicesAppStoreSubmissionRoute
  '/services/ios': typeof ServicesIosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/services/android': typeof ServicesAndroidRoute
  '/services/app-store-submission': typeof ServicesAppStoreSubmissionRoute
  '/services/ios': typeof ServicesIosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/services/android': typeof ServicesAndroidRoute
  '/services/app-store-submission': typeof ServicesAppStoreSubmissionRoute
  '/services/ios': typeof ServicesIosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/answers'
    | '/contact'
    | '/examples'
    | '/faq'
    | '/mcp'
    | '/services'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/email/unsubscribe'
    | '/services/android'
    | '/services/app-store-submission'
    | '/services/ios'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/answers'
    | '/contact'
    | '/examples'
    | '/faq'
    | '/mcp'
    | '/services'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/email/unsubscribe'
    | '/services/android'
    | '/services/app-store-submission'
    | '/services/ios'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/answers'
    | '/contact'
    | '/examples'
    | '/faq'
    | '/mcp'
    | '/services'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/email/unsubscribe'
    | '/services/android'
    | '/services/app-store-submission'
    | '/services/ios'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnswersRoute: typeof AnswersRoute
  ContactRoute: typeof ContactRoute
  ExamplesRoute: typeof ExamplesRoute
  FaqRoute: typeof FaqRoute
  McpRoute: typeof McpRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers': {
      id: '/answers'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ios': {
      id: '/services/ios'
      path: '/ios'
      fullPath: '/services/ios'
      preLoaderRoute: typeof ServicesIosRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/app-store-submission': {
      id: '/services/app-store-submission'
      path: '/app-store-submission'
      fullPath: '/services/app-store-submission'
      preLoaderRoute: typeof ServicesAppStoreSubmissionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/android': {
      id: '/services/android'
      path: '/android'
      fullPath: '/services/android'
      preLoaderRoute: typeof ServicesAndroidRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAndroidRoute: typeof ServicesAndroidRoute
  ServicesAppStoreSubmissionRoute: typeof ServicesAppStoreSubmissionRoute
  ServicesIosRoute: typeof ServicesIosRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAndroidRoute: ServicesAndroidRoute,
  ServicesAppStoreSubmissionRoute: ServicesAppStoreSubmissionRoute,
  ServicesIosRoute: ServicesIosRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnswersRoute: AnswersRoute,
  ContactRoute: ContactRoute,
  ExamplesRoute: ExamplesRoute,
  FaqRoute: FaqRoute,
  McpRoute: McpRoute,
  ServicesRoute: ServicesRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
